### ISSUE TITLE
Needs a License.

### ISSUE THREAD

**Issue by sanscore** [natetarrh/frogger#2]
Could you add a license to this project?

Just for fun, I am in the process of adding a few internal, single-purpose web apps at my work. So , I would like to add an instance of `frogger`, but there is *NO* license. Without a license, according to the legal team, one is only allowed to _view_ the source code. Github's ToS. according to choosealicense.com, gives its users express permission to "fork" projects. However, that does not consent _to-modify_ nor _to-execute_.

Personally, I prefer the MIT license, but for work-related OSS projects I use Apache 2.0.

* https://choosealicense.com/
* https://choosealicense.com/no-license/
* https://choosealicense.com/licenses/mit/
* https://choosealicense.com/licenses/apache-2.0/

**Comment by natetarrh** [comment]
Done, thank you!

**Comment by sanscore** [comment]
Awesome, Thanks!
